# Site settings
title: LumoLetters
email: info@lumoletters.com
description: >- # this means to ignore newlines until "baseurl:"
  LumoLetters provides personalized letters for seniors. Bringing joy and meaningful experiences to life.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://lumoletters.com" # the base hostname & protocol for your site
twitter_username: lumoletters
github_username: lumoletters # Corrected: use your actual GitHub username

# Build settings
plugins:
  - jekyll-feed

# ... other settings ...
font_awesome_url: "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css"


# Exclude from processing.
# The following items will not be processed, by default.
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

sass:
  style: compressed

# Include folders
include:
  - assets # Ensure assets are included
  - _pages
  - _user

# Optional: Add settings for your custom collections or paths
# collections:
#   mycollection:
#     output: true
#   anothercollection:
#     output: false

# Permalinks
permalink: /:title/ # Clean URLs

# Sitemap settings
sitemap:
  enabled: true

# Optional Google Analytics
# google_analytics: "UA-XXXXX-X"