[build]
  command = "npm run build"
  publish = "_site"
  functions = "netlify/functions"

[build.environment]
  JEKYLL_ENV = "production"
  NODE_VERSION = "20"

[dev]
  command = "npm run start"
  targetPort = 4001
  port = 8888
  publish = "_site"
  autoLaunch = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/error"
  to = "/error.html"
  status = 200

[[redirects]]
  from = "/api/webhooks/stripe"
  to = "/.netlify/functions/stripe-webhooks"
  status = 200
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https://js.stripe.com https://esm.sh http://localhost:35729; style-src 'self' 'unsafe-inline'; img-src 'self' data: https://*.stripe.com; object-src 'none'; connect-src 'self' https://dev-rfi7yfcndb5e8ycp.us.auth0.com https://api.stripe.com ws://localhost:35729; frame-src 'self' https://js.stripe.com https://hooks.stripe.com;"


[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"


[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/onboarding/welcome"
  to = "/welcome"
  status = 301

[[redirects]]
  from = "/app/dashboard"
  to = "/app/dashboard/"
  status = 301

[[redirects]]
  from = "/dashboard"
  to = "/app/dashboard/"
  status = 200
  force = true