[build]
  command = "bundle exec jekyll build"
  publish = "_site"

[build.environment]
  RUBY_VERSION = "3.3.6"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/user/*"
  to = "/index.html"
  status = 302 # 302 = found (redirect)
  force = false # no force needed, we do not want the user to have to be logged in to access the login page
  conditions = { Role = ["user"] }

[[redirects]]
 from = "/user/*"
 to = "/index.html"
 status = 302 # 302 = found (redirect)
 force = false # no force needed, we do not want the user to have to be logged in to access the login page


[[redirects]]
  from = "/dashboard/*"
  to = "/index.html"
  status = 302 # 302 = found (redirect)
  force = false # no force needed, we do not want the user to have to be logged in to access the login page
  conditions = { Role = ["user"] }


[[redirects]]
  from = "/dashboard/*"
  to = "/index.html"
  status = 302 # 302 = found (redirect)
  force = false # no force needed, we do not want the user to have to be logged in to access the login page