[build]
  command = "bundle exec jekyll build"
  publish = "_site"

[build.environment]
  RUBY_VERSION = "3.3.6"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

# Redirect unauthenticated users from /dashboard/* to the login page
[[redirects]]
  from = "/dashboard/*"
  to = "/login"
  status = 302
  force = false
  conditions = { Role = ["user"] }

# Redirect unauthenticated users from /user/* to the login page
[[redirects]]
  from = "/user/*"
  to = "/login"
  status = 302
  force = false
  conditions = { Role = ["user"] }

# You can also add this to redirect any other unauthenticated paths:
[[redirects]]
  from = "/user/dashboard/*"
  to = "/login"
  status = 302
  force = false
  conditions = { Role = ["user"] }